// RBUBANK — Core Financial Ledger & User State
// Configured for Denis Rech (Founder Metal Tier)
// Compliant with European SEPA / Neobank architectural models

export const INITIAL_USER = {
  name: "Denis Rech",
  firstName: "Denis",
  handle: "@denrech",
  email: "denis@rbubank.eu",
  phone: "+49 170 882 9104",
  tier: "Black Metal Founder",
  avatarInitials: "DR",
  isVerified: true,
  accountNumber: "4405320130",
  iban: "DE89 3704 0044 0532 0130 00",
  bic: "RBUBDEFFXXX",
  routingNumber: "37040044",
  currency: "USD",
  balances: {
    USD: 38420.50,
    EUR: 35248.16,
    GBP: 30190.20,
    CHF: 34105.80
  },
  metrics: {
    annualInflowTotal: 81400.00,
    annualInflowCount: 12,
    monthlyAverageInflow: 6783.33,
    annualOutflowTotal: 48250.00,
    netSavings: 33150.00,
    savingsYieldRate: 4.8 // 4.8% APY
  },
  cards: [
    {
      id: "card-metal-1",
      type: "physical",
      tier: "Black Obsidian Metal",
      brand: "Mastercard World Elite",
      number: "4532 8901 3342 8821",
      numberMasked: "•••• •••• •••• 8821",
      expiry: "09/29",
      cvv: "842",
      holder: "DENIS RECH",
      isFrozen: false,
      isPinRevealed: false,
      monthlyLimit: 25000,
      spentThisMonth: 6420.50,
      contactlessEnabled: true,
      onlinePurchasesEnabled: true,
      atmWithdrawalsEnabled: true,
      colorGradient: "linear-gradient(135deg, #181c26 0%, #080a0f 100%)",
      accentGlow: "rgba(0, 242, 254, 0.25)"
    },
    {
      id: "card-virtual-1",
      type: "virtual",
      tier: "Cyber Holographic Virtual",
      brand: "Visa Infinite",
      number: "4111 5678 9012 4190",
      numberMasked: "•••• •••• •••• 4190",
      expiry: "12/28",
      cvv: "319",
      holder: "DENIS RECH",
      isFrozen: false,
      isPinRevealed: false,
      monthlyLimit: 10000,
      spentThisMonth: 1280.00,
      contactlessEnabled: true,
      onlinePurchasesEnabled: true,
      atmWithdrawalsEnabled: false,
      colorGradient: "linear-gradient(135deg, #1e1136 0%, #0d061c 100%)",
      accentGlow: "rgba(138, 43, 226, 0.3)"
    }
  ],
  vaults: [
    {
      id: "vault-1",
      title: "Treasury & High-Yield Reserve",
      balance: 14500.00,
      target: 25000.00,
      apy: 4.8,
      currency: "USD",
      icon: "vault",
      color: "var(--accent-cyan)"
    },
    {
      id: "vault-2",
      title: "Porsche 911 GT3 Allocation",
      balance: 8000.00,
      target: 180000.00,
      apy: 4.8,
      currency: "USD",
      icon: "car",
      color: "var(--accent-emerald)"
    },
    {
      id: "vault-3",
      title: "St. Moritz Winter Chalet",
      balance: 2000.00,
      target: 6000.00,
      apy: 4.8,
      currency: "USD",
      icon: "mountain",
      color: "var(--accent-violet)"
    }
  ],
  recentRecipients: [
    { id: "rec-1", name: "Elena V.", handle: "@elena_v", avatar: "EV", bank: "Deutsche Bank", iban: "DE44 5001 0517 ... 9012" },
    { id: "rec-2", name: "Lukas Meyer", handle: "@lukas_ch", avatar: "LM", bank: "UBS Zurich", iban: "CH93 0024 0240 ... 4410" },
    { id: "rec-3", name: "Alex Tech", handle: "@alex_cto", avatar: "AT", bank: "Revolut Ltd", iban: "GB82 REVO 0099 ... 7821" },
    { id: "rec-4", name: "Sophie Bernard", handle: "@sophie_fr", avatar: "SB", bank: "BNP Paribas", iban: "FR76 3000 4001 ... 1120" }
  ]
};

// 12 Months of Monthly Aggregates (Sept 2025 - Sept 2026)
// Consistent monthly inflows of $6,000 - $8,500 totaling exactly $81,400.00
export const MONTHLY_SUMMARY = [
  { month: "Oct 25", label: "October 2025", inflow: 6400, outflow: 3950, net: 2450 },
  { month: "Nov 25", label: "November 2025", inflow: 6800, outflow: 4100, net: 2700 },
  { month: "Dec 25", label: "December 2025", inflow: 7500, outflow: 4800, net: 2700 },
  { month: "Jan 26", label: "January 2026", inflow: 6200, outflow: 3700, net: 2500 },
  { month: "Feb 26", label: "February 2026", inflow: 6900, outflow: 3850, net: 3050 },
  { month: "Mar 26", label: "March 2026", inflow: 7100, outflow: 4200, net: 2900 },
  { month: "Apr 26", label: "April 2026", inflow: 6300, outflow: 3650, net: 2650 },
  { month: "May 26", label: "May 2026", inflow: 6700, outflow: 4100, net: 2600 },
  { month: "Jun 26", label: "June 2026", inflow: 6800, outflow: 3900, net: 2900 },
  { month: "Jul 26", label: "July 2026", inflow: 7200, outflow: 4300, net: 2900 },
  { month: "Aug 26", label: "August 2026", inflow: 7100, outflow: 4100, net: 3000 },
  { month: "Sep 26", label: "September 2026", inflow: 6400, outflow: 3600, net: 2800 }
];

// Complete Real-world Neobanking Transactions Ledger
export const INITIAL_TRANSACTIONS = [
  {
    id: "tx-2026-09-02-1",
    date: "2026-09-02",
    time: "14:28",
    title: "European FinTech Advisory Retainer",
    counterparty: "Venture FinTech Partners AG (Zurich)",
    category: "Income",
    amount: 6400.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "RBU-SEPA-8890214",
    icon: "arrow-down-left",
    note: "Monthly strategic engineering & advisory retainer Q3",
    clearingHouse: "EBA CLEARING / RT1 Instant"
  },
  {
    id: "tx-2026-09-01-1",
    date: "2026-09-01",
    time: "10:15",
    title: "Düsseldorf Prime Penthouse Rent",
    counterparty: "Immobilien Königsallee GmbH",
    category: "Housing",
    amount: -2450.00,
    currency: "USD",
    type: "outflow",
    status: "completed",
    paymentMethod: "SEPA Direct Debit",
    referenceCode: "SDD-KALL-2026-09",
    icon: "home",
    note: "Monthly residence lease Königsallee 42",
    clearingHouse: "SEPA Core Direct Debit"
  },
  {
    id: "tx-2026-08-28-1",
    date: "2026-08-28",
    time: "18:42",
    title: "Apple Store Kurfürstendamm",
    counterparty: "Apple Retail Germany B.V. & Co. KG",
    category: "Tech & Software",
    amount: -1899.00,
    currency: "USD",
    type: "outflow",
    status: "completed",
    paymentMethod: "Apple Pay / Metal Debit",
    referenceCode: "POS-APPL-BER-993",
    icon: "laptop",
    note: "MacBook Pro M-Series hardware workstation upgrade",
    clearingHouse: "Mastercard Global Network"
  },
  {
    id: "tx-2026-08-24-1",
    date: "2026-08-24",
    time: "12:10",
    title: "ATM Cash Withdrawal Zurich",
    counterparty: "Euronet ATM Bahnhofstrasse",
    category: "Cash & ATM",
    amount: -500.00,
    currency: "USD",
    type: "outflow",
    status: "completed",
    paymentMethod: "Mastercard Metal Debit",
    referenceCode: "ATM-ZUR-4412",
    icon: "banknote",
    note: "Cash withdrawal CHF 450 (0% RBU FX fee)",
    clearingHouse: "SIX Swiss Exchange / Euronet"
  },
  {
    id: "tx-2026-08-15-1",
    date: "2026-08-15",
    time: "09:30",
    title: "Distributed Systems Architecture Contract",
    counterparty: "Apex Systems Global Ltd",
    category: "Income",
    amount: 7100.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SWIFT Wire",
    referenceCode: "SWIFT-APEX-771049",
    icon: "arrow-down-left",
    note: "Milestone completion: Core backend high-throughput mesh",
    clearingHouse: "SWIFT GPI Instant Settlement"
  },
  {
    id: "tx-2026-08-12-1",
    date: "2026-08-12",
    time: "20:45",
    title: "Restaurant Tim Raue (Berlin)",
    counterparty: "Restaurant Tim Raue GmbH",
    category: "Dining",
    amount: -385.00,
    currency: "USD",
    type: "outflow",
    status: "completed",
    paymentMethod: "Mastercard Metal Debit",
    referenceCode: "POS-TR-BER-2041",
    icon: "utensils",
    note: "Business tasting menu dinner with investor partners",
    clearingHouse: "Mastercard Global Network"
  },
  {
    id: "tx-2026-08-08-1",
    date: "2026-08-08",
    time: "11:20",
    title: "Transfer to Elena V.",
    counterparty: "Elena Volkova (@elena_v)",
    category: "Transfers",
    amount: -450.00,
    currency: "USD",
    type: "outflow",
    status: "completed",
    paymentMethod: "Internal RBU P2P",
    referenceCode: "RBU-P2P-ELENA-01",
    icon: "send",
    note: "Shared Zurich private villa weekend split",
    clearingHouse: "RBU Instant P2P Ledger"
  },
  {
    id: "tx-2026-08-04-1",
    date: "2026-08-04",
    time: "15:10",
    title: "AWS Cloud Infrastructure EMEA",
    counterparty: "Amazon Web Services EMEA SARL",
    category: "Tech & Software",
    amount: -420.00,
    currency: "USD",
    type: "outflow",
    status: "completed",
    paymentMethod: "Cyber Virtual Card",
    referenceCode: "INV-AWS-EMEA-841",
    icon: "cloud",
    note: "GPU clusters and Frankfurt low-latency nodes",
    clearingHouse: "Visa Direct"
  },
  {
    id: "tx-2026-07-28-1",
    date: "2026-07-28",
    time: "16:05",
    title: "Lufthansa Business Class Flight",
    counterparty: "Deutsche Lufthansa AG",
    category: "Travel & Transport",
    amount: -640.00,
    currency: "USD",
    type: "outflow",
    status: "completed",
    paymentMethod: "Apple Pay / Metal Debit",
    referenceCode: "TKT-LH-FRA-ZRH-88",
    icon: "plane",
    note: "Frankfurt to Zurich European Fintech Summit",
    clearingHouse: "Mastercard Global Network"
  },
  {
    id: "tx-2026-07-16-1",
    date: "2026-07-16",
    time: "11:00",
    title: "European SaaS Platform Distribution",
    counterparty: "Nordic Tech Ventures Fund III",
    category: "Income",
    amount: 7200.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "RBU-SEPA-720194",
    icon: "arrow-down-left",
    note: "Q2 SaaS Profit Sharing & Advisory Payout",
    clearingHouse: "EBA CLEARING / RT1 Instant"
  },
  {
    id: "tx-2026-06-25-1",
    date: "2026-06-25",
    time: "14:15",
    title: "P2P Settlement to Wise / Revolut",
    counterparty: "Wise Europe SA",
    category: "Transfers",
    amount: -1200.00,
    currency: "USD",
    type: "outflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "WISE-EUR-884102",
    icon: "refresh-cw",
    note: "Interbank cross-border liquidity transfer",
    clearingHouse: "SEPA Instant Credit Transfer"
  },
  {
    id: "tx-2026-06-14-1",
    date: "2026-06-14",
    time: "10:45",
    title: "Fintech Systems Architecture Advisory",
    counterparty: "Helvetia Digital Banking Labs",
    category: "Income",
    amount: 6800.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "RBU-SEPA-680412",
    icon: "arrow-down-left",
    note: "Core architecture review & regulatory sandbox design",
    clearingHouse: "EBA CLEARING / RT1 Instant"
  },
  {
    id: "tx-2026-05-18-1",
    date: "2026-05-18",
    time: "13:20",
    title: "High-Volume Consulting Contract",
    counterparty: "Continental Enterprise Software",
    category: "Income",
    amount: 6700.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "RBU-SEPA-670119",
    icon: "arrow-down-left",
    note: "Monthly engineering advisory retainer",
    clearingHouse: "EBA CLEARING / RT1 Instant"
  },
  {
    id: "tx-2026-04-15-1",
    date: "2026-04-15",
    time: "09:50",
    title: "Venture Advisory & Technology Retainer",
    counterparty: "Berlin Angel Syndicate Ltd",
    category: "Income",
    amount: 6300.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "RBU-SEPA-630855",
    icon: "arrow-down-left",
    note: "Angel portfolio technical audits & advisory",
    clearingHouse: "EBA CLEARING / RT1 Instant"
  },
  {
    id: "tx-2026-03-12-1",
    date: "2026-03-12",
    time: "16:40",
    title: "Software Licensing & Consulting Retainer",
    counterparty: "Quantum Logic AG (Geneva)",
    category: "Income",
    amount: 7100.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "RBU-SEPA-710924",
    icon: "arrow-down-left",
    note: "High-frequency trading interface design consult",
    clearingHouse: "EBA CLEARING / RT1 Instant"
  },
  {
    id: "tx-2026-02-14-1",
    date: "2026-02-14",
    time: "11:15",
    title: "Cloud Native Scalability Retainer",
    counterparty: "Alpine Cloud Solutions Sarl",
    category: "Income",
    amount: 6900.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "RBU-SEPA-690220",
    icon: "arrow-down-left",
    note: "Kubernetes multi-region failover advisory",
    clearingHouse: "EBA CLEARING / RT1 Instant"
  },
  {
    id: "tx-2026-01-16-1",
    date: "2026-01-16",
    time: "10:30",
    title: "Q1 Tech Strategy Advisory Payout",
    counterparty: "European FinTech Partners AG",
    category: "Income",
    amount: 6200.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "RBU-SEPA-620401",
    icon: "arrow-down-left",
    note: "Neobanking regulatory framework consulting",
    clearingHouse: "EBA CLEARING / RT1 Instant"
  },
  {
    id: "tx-2025-12-18-1",
    date: "2025-12-18",
    time: "15:00",
    title: "Annual SaaS Performance Bonus & Retainer",
    counterparty: "Venture FinTech Partners AG",
    category: "Income",
    amount: 7500.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "RBU-SEPA-750891",
    icon: "arrow-down-left",
    note: "End-of-year milestone & advisory bonus",
    clearingHouse: "EBA CLEARING / RT1 Instant"
  },
  {
    id: "tx-2025-11-15-1",
    date: "2025-11-15",
    time: "14:20",
    title: "Distributed Systems Architecture Retainer",
    counterparty: "Apex Systems Global Ltd",
    category: "Income",
    amount: 6800.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "RBU-SEPA-680902",
    icon: "arrow-down-left",
    note: "Distributed database replication consulting",
    clearingHouse: "EBA CLEARING / RT1 Instant"
  },
  {
    id: "tx-2025-10-14-1",
    date: "2025-10-14",
    time: "12:00",
    title: "FinTech Product Architecture Advisory",
    counterparty: "Helvetia Digital Banking Labs",
    category: "Income",
    amount: 6400.00,
    currency: "USD",
    type: "inflow",
    status: "completed",
    paymentMethod: "SEPA Instant",
    referenceCode: "RBU-SEPA-640182",
    icon: "arrow-down-left",
    note: "Modern cross-border settlement architecture",
    clearingHouse: "EBA CLEARING / RT1 Instant"
  }
];

// Helper to format currency
export function formatCurrency(amount, currency = "USD") {
  const symbol = currency === "EUR" ? "€" : currency === "GBP" ? "£" : currency === "CHF" ? "CHF " : "$";
  const abs = Math.abs(amount);
  const formatted = abs.toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  });
  return `${amount < 0 ? "-" : ""}${symbol}${formatted}`;
}
